---
- name: Cleanup Schedules
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: Get Pre Check Schedules
      ansible.builtin.uri:
        url: "{{ controller_uri }}/api/v2/job_templates/{{ pre_check_template_id }}/schedules/"
        body_format: json
        validate_certs: false
        return_content: true
        method: GET
        status_code: [200, 201]
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ controller_token }}"
      register: pre_check_schedules

    - name: Cleanup Pre Check Schedules
      ansible.builtin.uri:
        url: "{{ controller_uri }}/api/v2/schedules/{{ item.id }}/"
        body_format: json
        validate_certs: false
        return_content: true
        method: DELETE
        status_code: [200, 201, 204]
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ controller_token }}"
      loop: "{{ pre_check_schedules.json.results | selectattr('next_run','none') }}"

    - name: Get Patch Schedules
      ansible.builtin.uri:
        url: "{{ controller_uri }}/api/v2/job_templates/{{ patch_template_id }}/schedules/"
        body_format: json
        validate_certs: false
        return_content: true
        method: GET
        status_code: [200, 201]
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ controller_token }}"
      register: patch_schedules

    - name: Cleanup Patch Schedules
      ansible.builtin.uri:
        url: "{{ controller_uri }}/api/v2/schedules/{{ item.id }}/"
        body_format: json
        validate_certs: false
        return_content: true
        method: DELETE
        status_code: [200, 201, 204]
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ controller_token }}"
      loop: "{{ patch_schedules.json.results | selectattr('next_run','none') }}"
