---
- name: Create Schedules
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    api+host: "http://127.0.0.1:8080/patch/"
  tasks:
    # Using shell as ansible_date_time fact returns UTC
    - name: Set update date
      shell: "date +'%Y-%m-%d' -d '+7 days'"
      register: shell_update_date

    - name: Set update date
      set_fact:
        update_date: "{{ shell_update_date.stdout }}"

    - name: Query filter
      debug:
        var: update_date

    - name: Get hosts from API
      ansible.builtin.uri:
        url: "{{ api_host}}/date/{{ update_date }}"
        return_content: true
      register: api_results

    - name: Add hosts to Inventory
      ansible.builtin.add_host:
        name: "{{ item.Server }}"
        groups: pre_check
        id: "{{ item.ID }}"
      loop: "{{ api_results.content }}"

- name: Run pre checks
  hosts: pre_check
  connection: local
  vars:
    api_host: "http://127.0.0.1:8080/patch/"
  tasks:
    - name: Pause for 2 minutes to simulate pre checks
      ansible.builtin.pause:
        minutes: 2

    - name: Update API - Pre Checks Complete
      ansible.builtin.uri:
        url: "{{ api_host}}/{{ item.ID }}"
        method: PUT
        body: '{"Status": "PreCheckCompleted", "PreCheckStatus": "2", "PreCheckJobID": "{{ tower_job_id}}" }'
