---
- name: Create Schedules
  hosts: 127.0.0.1
  connection: local
  vars:
    api_host: "http://192.168.122.12:8080/patch"
  tasks:
    - name: Set update date query
      set_fact:
        update_date: "{{ '%Y-%m-%d' | strftime( (ansible_date_time.epoch|int) + (60*60*24*7) ) }}"

    - name: Get hosts from API
      ansible.builtin.uri:
        url: "{{ api_host}}/date/{{ update_date }}"
        return_content: true
      register: api_results

    - name: Get pre check schedules
      ansible.builtin.uri:
        url: "{{ controller_uri }}/api/v2/job_templates/{{ pre_check_template_id }}/schedules/"
        body_format: json
        validate_certs: false
        return_content: true
        method: GET
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ controller_token }}"
      register: pre_check_schedules_data

    - name: Set pre_check_schedules fact
      set_fact:
        pre_check_schedules: "{{ pre_check_schedules_data.json.results }}"

    - name: Get patch schedules
      ansible.builtin.uri:
        url: "{{ controller_uri }}/api/v2/job_templates/{{ patch_template_id }}/schedules/"
        body_format: json
        validate_certs: false
        return_content: true
        method: GET
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ controller_token }}"
      register: patch_schedules_data

    - name: Set patch_schedules fact
      set_fact:
        patch_schedules: "{{ patch_schedules_data.json.results }}"

    - name: Build schedules
      include_tasks: build_schedules_api.yaml
      loop: "{{ api_results.json }}"
