---
- name: Create Schedules
  hosts: 127.0.0.1
  connection: local
  vars:
    db_host: 192.168.122.12
    db_port: 3306
  tasks:
    - name: Set update date query
      set_fact:
        update_date: "{{ '%Y-%m-%d' | strftime( (ansible_date_time.epoch|int) + (60*60*24*8) ) }}"

    - name: Get hosts from MySQL
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_db: patching
        login_user: root
        login_password: "{{ mysql_passwd }}"
        login_port: "{{ db_port }}"
        query: 'select * from patch where update_time like "{{ update_date }}%";'
      register: mysql_results

    - name: Build schedules
      include_tasks: build_schedules.yaml
      loop: "{{ mysql_results.query_result[0] }}"
