---
- name: Create Schedules
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Set update date query
      shell: date -d "+ 1 month" "+%Y-%m-%d 23:59:59"
      register: update_date_shell

    - name: Set update_date fact
      set_fact:
        update_date: "{{ update_date_shell.stdout }}"

    - name: Get hosts from MySQL
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_db: patching
        login_user: root
        login_password: "{{ mysql_passwd }}"
        login_port: "{{ db_port }}"
        query: 'select * from patch where DATE(update_time) <= "{{ update_date }}%" and status = "Booked";'
      register: mysql_results

    - name: Build schedules
      include_tasks: build_schedules.yaml
      loop: "{{ mysql_results.query_result[0] }}"
