---
- name: Create Schedules
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Set update date query
      shell: date -d "+ 30 days" "+%Y-%m-%d %H:%M:00"
      register: update_date_shell

    - name: Set update_date fact
      set_fact:
        update_date: "{{ update_date_shell.stdout }}"

    - name: Get patch times from MySQL
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_db: patching
        login_user: root
        login_password: "{{ mysql_passwd }}"
        login_port: "{{ db_port }}"
        query: 'select distinct(update_time) from patch where update_time <= "{{ update_date }}" and pre_checks_created <= 0 or update_time <= "{{ update_date }}" and patch_created <= 0 order by update_time asc limit 500;'
      register: mysql_results

    - debug:
        var: mysql_results.query_result[0]

    - name: Build schedules
      include_tasks: build_schedules.yaml
      loop: "{{ mysql_results.query_result[0] }}"
