---
- name: Test logs
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Create hostname dir in log dir
      ansible.builtin.file:
        path: "/mnt/{{ inventory_hostname }}"
        state: directory
        mode: "0755"
    - name: Echo random words to a log file
      shell: echo "this is a test" >> "/mnt/{{ inventory_hostname }}/{{ patch_version }}.log"
    - name: Pause for 5 minutes
      pause:
        minutes: 5
